# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: "[PROD] Site"
    url: https://testfy.com.br/
  - name: "[PROD] ECommerce"
    url: https://store.testfy.com.br/
  - name: "[PROD] Professionals"
    url: https://professionals.testfy.com.br/
  - name: "[PROD] Workspace"
    url: http://workspace.testfy.com.br/
  - name: "[STAGE] API (nova)"
    url: https://api-stage.testfy.com.br/public/healthcheck/liveness
  - name: "[STAGE] Backoffice (novo)"
    url: https://workspace-stage.testfy.com.br/
  - name: "[STAGE] Store (nova)"
    url: https://store-stage.testfy.com.br/
    

assignees:
  - FeMaffezzolli

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: hub-xp.github.io/testfy-status/
  baseUrl: /testfy-status
  logoUrl: https://assets.testfy.com.br/static/img/logo2.svg
  name: Testfy
  apiBaseUrl: https://raw.githubusercontent.com/hub-xp/testfy-status
  introTitle: "**Status** page da Testfy"
  introMessage: Acompanhe o status de todos os serviços.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/hub-xp/testfy-status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"
