# Change these first
owner: hub-xp # Your GitHub organization or username, where this repository lives
repo: testfy-status # The name of this repository

sites:
  - name: "[PROD] Site e Loja"
    url: https://testfy.com.br/
  - name: "[PROD] Professionals"
    url: https://pro.testfy.com.br/
  - name: "[PROD] Workspace"
    url: http://workspace.testfy.com.br/
  - name: "[PROD] API"
    url: https://api.testfy.com.br/public/healthcheck/liveness
  - name: "[STAGE] Backoffice (novo)"
    url: https://workspace-stage.testfy.com.br/
  - name: "[STAGE] Store (nova)"
    url: https://store-stage.testfy.com.br/
  - name: "[PROD] Portainer"
    url: https://portainer.testfy.com.br/
    

assignees:
  - FeMaffezzolli

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: hub-xp.github.io/testfy-status/
  baseUrl: /testfy-status
  logoUrl: https://assets.testfy.com.br/static/img/logo2.svg
  name: Testfy
  introTitle: "**Status** page da Testfy"
  introMessage: Acompanhe o status de todos os serviços.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/hub-xp/testfy-status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"
